/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-04-17T02:53:03.766Z")

@Api(value = "hello", description = "the hello API")
public interface HelloApi {

    @ApiOperation(value = "", nickname = "helloUserGet", notes = "Returns a greeting to the user!", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns the greeting.", response = String.class),
        @ApiResponse(code = 400, message = "Invalid characters in \"user\" were provided.") })
    @RequestMapping(value = "/hello/{user}",
        method = RequestMethod.GET)
    ResponseEntity<String> helloUserGet(@ApiParam(value = "The name of the user to greet.",required=true) @PathVariable("user") String user);

}
